version: '3'

services:
  nut-container:
    container_name: nut-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000  # Set the desired user ID
        GROUP_ID: 20  # Set the desired group ID
#    restart: always
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
#    privileged: true

