services:
  nobreak-nut:
    container_name: nobreak-nut
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    user: "nut"
    group_add:
      - dialout
    volumes:
      - ./nut/etc:/etc/nut
      - ./nut/data:/var/lib/nut
    ports:
      - '3493:3493'
