services:
  nobreak-nut:
    container_name: nobreak-nut
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 0  # Set the desired user ID
#        GROUP_ID: 1000  # Set the desired group ID
    deploy:
      resources:
        limits:
          memory: 256M
          memory_swap: 512M
    restart: always
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - '3493:3493'
