services:
  nobreak-nut:
    container_name: nobreak-nut
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 0  # Set the desired user ID
        # GROUP_ID: 1000  # Set the desired group ID
    restart: unless-stopped
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    group_add:
      - dialout
    ports:
      - '3493:3493'
